#!/usr/bin/python
import sys
from randomguess import RandomGuess
import random
from utilities import logging, load_data, cross_validation


def train(docs, labels):
    model = RandomGuess()
    model.train(docs, labels)
    model.save_model("randomguess.dat")
    return model


def main(model=None):
    docs = sys.stdin.readlines()
    if not model:
        model = RandomGuess('randomguess.dat')
    for doc in docs:
        print model.predict(doc)

if __name__ == "__main__":
    # main()
    docs, labels = load_data('data/dev_text.txt', 'data/dev_label.txt')
    # main(train(docs, labels))
    cross_validation(RandomGuess(), docs, labels, 10)
